services:

  redis:
    image: redis:7-alpine          
    container_name: aoe-stats-redis 
    ports:
      - "6379:6379"                
    volumes:
      - redis_data:/data           
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    restart: unless-stopped        
    healthcheck:                   
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3


  redis-ui:
    image: rediscommander/redis-commander:latest
    container_name: aoe-stats-redis-ui
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - tools
    restart: unless-stopped

volumes:
  redis_data:
    driver: local